name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install -g markdown-it

      - name: Convert Markdown to HTML
        run: |
          cat > convert.js << 'EOL'
          const fs = require('fs');
          const MarkdownIt = require('markdown-it');
          const anchor = require('markdown-it-anchor');
          
          const md = new MarkdownIt()
            .use(anchor, {
              permalink: anchor.permalink.ariaHidden({
                placement: 'before'
              })
            });
          
          const readme = fs.readFileSync('README.md', 'utf8');
          const html = md.render(readme);
          
          const fullHtml = `
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Awesome Simulation Theory</title>
              <link rel="stylesheet" href="styles.css">
            </head>
            <body>
              <div class="container">
                ${html}
              </div>
            </body>
          </html>`;
          
          fs.writeFileSync('_site/index.html', fullHtml);
          EOL

      - name: Convert Markdown to HTML
        run: node convert.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
